FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["SiteTransporteNovo.csproj", "./"]
RUN dotnet restore "SiteTransporteNovo.csproj"
COPY . .
WORKDIR "/src/"
RUN dotnet build "SiteTransporteNovo.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "SiteTransporteNovo.csproj" -c Release -o /app/publish /p:PublishReadyToRun=true

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "SiteTransporteNovo.dll"]